### PR TITLE
Topic subscription with wildcard and placeholders

### PR DESCRIPTION
**Pull request by H3adcra5h**
This is a new implementation with wildcards and named placeholders, without user created regex.

### CODE REVIEW

**Comment by H3adcra5h** [comment]
I cannot fix the checks, no idea what happens.

**Comment by koenvervloesem** [comment]
This looks nice! The only thing I would change at first sight is the custom_data attribute of the TopicData class: I would call it data to prevent confusion with the custom data field in Hermes sessions.

**Comment by H3adcra5h** [comment]
done

**Comment by H3adcra5h** [comment]
I have no idea how I can fix this:
**_rhasspyhermes_app/__init__.py:197:46: W605 invalid escape sequence '\w'_**
It works and the outcome is ok. If I escape this like _**'\\w'**_ the outcome is wrong.

**Comment by H3adcra5h** [comment]
I optimized the topic parsing and fixed my mypy errors. Hopefully it's running as expected, too late to test it intensively.

Two errors are from your classes. Maybe you understand this article [**Unexpected errors about ‘None’ and/or ‘Optional’ types**](https://mypy.readthedocs.io/en/stable/common_issues.html#unexpected-errors-about-none-and-or-optional-types). I'm not able to.

**Pull request closed without merging**
